{% set name = "dask" %}
{% set version = "2023.2.0" %}
{% set build_number = "0" %}
{% set checksum = "c0716193e0e197bc541199e41770b4f2f7df6c137bb94e5b4812cfdc6cbe0a84" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}
build:
  number: {{ build_number }}
  skip: true # [py<38]

requirements:
  host:
    - python
  run:
    - python
    - bokeh >=2.4.2,<3.0
    - cytoolz >=0.8.2
    - dask-core {{ version }}
    - distributed {{ version }}
    - jinja2
    - lz4
    - numpy >=1.18
    - pandas >=1.0
  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.io
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed
  requires:
    - pip
  commands:
    - pip check

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core --->distributed --->dask

about:
  home: https://dask.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parallel PyData with Task Scheduling
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://dask.org/
  doc_source_url: https://github.com/dask/dask/tree/main/docs
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - koverholt
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - jrbourbeau
