{% set name = "dask" %}
{% set version = "2023.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9dc72ebb509f58f3fe518c12dd5a488c67123fdd66ccb0b968b34fd11e512153
build:
  number: 0
  skip: true # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - bokeh >=2.4.2,<3.0
    - click >=8.0
    - cloudpickle >=1.5.1
    - cytools >=0.10.0
    - dask-core {{ version }}
    - distributed {{ version }}
    - fsspec >=2021.09.0
    - importlib-metadata >=4.13.0
    - jinja2 >=2.10.3
    - numpy >=1.21
    - packaging >=20.0
    - pandas >=1.3
    - partd >=1.2.0
    - pyyaml >=5.3.1
  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.io
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed
  requires:
    - pip
  commands:
    - pip check

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core --->distributed --->dask

about:
  home: https://www.dask.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parallel PyData with Task Scheduling
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://docs.dask.org/en/stable/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - koverholt
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - jrbourbeau
