{% set version = "0.10.0" %}

package:
  name: dask
  version: "{{ version }}"

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  md5: 581c3f23c46eea79a1b68aed4579d57a

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bokeh
    - cloudpickle >=0.2.1
    - distributed >=1.11.0
    - numpy
    - pandas >=0.18.0
    - partd >=0.3.3
    - toolz >=0.7.2

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.store

about:
  home: http://github.com/dask/dask/
  license: BSD 3-Clause
  summary: 'Minimal task scheduling abstraction'

extra:
  recipe-maintainers:
    - mrocklin
    - jcrist
    - koverholt
