{% set version = "0.15.2" %}

package:
  name: dask
  version: "{{ version }}"

build: 
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bokeh
    - cloudpickle >=0.2.1
    - dask-core {{ version }}
    - distributed >=1.16.0
    - numpy
    - pandas >=0.19.0
    - partd >=0.3.8
    - toolz >=0.7.3

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

about:
  home: http://github.com/dask/dask/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Parallel Python with task scheduling'

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - koverholt
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
