{% set name = "dask" %}
{% set version = "2023.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51009e92ba9a280bd417633d1ae84f3ed23a8940f0a19594a4b7797ef226fff4
build:
  number: 0
  skip: true # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - bokeh >=2.4.2,<3.0
    - cytoolz >=0.8.2
    - dask-core {{ version }}
    - distributed {{ version }}
    - jinja2 >=2.10.3
    - lz4
    - numpy >=1.21
    - pandas >=1.3
    - click >=7.0
    - cloudpickle >=1.1.1
    - fsspec >=0.6.0
    - packaging >=20.0
    - partd >=1.2.0
    - pyyaml >=5.3.1
    - importlib-metadata >=4.13.0
  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.io
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed
  requires:
    - pip
  commands:
    - pip check

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core --->distributed --->dask

about:
  home: https://www.dask.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parallel PyData with Task Scheduling
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://docs.dask.org/en/stable/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - koverholt
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - jrbourbeau
